name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Build and test
      run: |
        cd frontend
        npm run build
        cd ../backend
        npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Copy built files
      run: |
        cp -r frontend/build/ react-node-app/

    - name: Install dependencies
      run: npm install 
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
           cd /var/www/html/react-node-app
           git pull origin main
