name: react and node CI/CD

on:
  push:
    branches:
      - main

jobs:

  node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install and Run node dependencies
      run:  npm install
  
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/react-node-app
            git pull origin main
