name: React and Node.js CI/CD

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build React frontend
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app
        run: npm run build
        working-directory: frontend

      - name: Archive frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: frontend/build
          
      # Build Node.js backend
      - name: Install backend dependencies
        run: npm install
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Download frontend build artifacts
      - name: Download frontend build artifacts
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: frontend/build

      - name: Copy frontend build artifacts to deployment directory
        run: |
          sudo cp -r /var/www/html/frontend/build/* /var/www/html/react-node-app/frontend/build/

      # Deploy backend files to server
      - name: Deploy backend to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: backend/*
          target: /var/www/html/react-node-app/
